# Generated by Django 5.1.2 on 2024-12-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0007_asset_asset_key_highlights_commitmentdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicprompts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userchatlogin',
            options={'managed': False},
        ),
    ]
