# Generated by Django 5.1.2 on 2025-01-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0008_alter_basicprompts_options_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicprompts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userchatlogin',
            options={'managed': True},
        ),
    ]
