# Generated by Django 5.1.2 on 2025-01-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0009_alter_basicprompts_options_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='token',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='token',
            new_name='user_id',
        ),
    ]
