# Generated by Django 5.1.2 on 2025-02-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0010_rename_token_chatsession_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicprompts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userchatlogin',
            options={'managed': False},
        ),
    ]
